---  
- name: Declarative Onboarding Demo - initial builds and upgrades
  
  hosts: localhost
  gather_facts: no
  vars:
    bigip_password: admin
    bigip_username: admin
    bigip_ip_guest1: 10.146.142.10
    bigip_ip_guest2: 10.146.142.11
    bigip_port: 443
    DO_rpm: f5-declarative-onboarding-1.10.0-2.noarch.rpm
    as3_rpm: f5-appsvcs-3.17.1-1.noarch.rpm

  tasks:

  - name: "Upload and install DO rpm to guests"
    bigip_lx_package:
      package: "../rpms/{{DO_rpm}}"
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "Upload and install AS3 rpm to guests"
    bigip_lx_package:
      package: "../rpms/{{as3_rpm}}"
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "BIG-IP Command - turboflex profile"
    bigip_command:
      commands:
        - "modify sys turboflex profile-config type turboflex-security"  #v13
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "Provision afm"
    bigip_provision:
      module: afm
      level: nominal
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "Provision avr"
    bigip_provision:
      module: avr
      level: nominal
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "Wait a maximum of 300 seconds for BIG-IPs to be ready to take configuration"
    bigip_wait:
      timeout: 300
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "BIG-IP Command on guests - pre-DO"
    bigip_command:
      commands:
        - "modify cli preference prompt { host user status current-folder config-sync-status }"
        - "modify cli global-settings service number"
        - "modify sys software update auto-check disabled"
        - "modify sys sshd allow replace-all-with { 10.0.0.0/255.0.0.0 192.168.0.0/255.255.0.0 172.16.0.0/255.240.0.0}"
        - "modify sys global-settings gui-security-banner-text \"************************************************************************************ This system (including all hardware, software, and peripheral equipment) is private property. ************************************************************************************\""
        - "modify sys global-settings gui-security-banner enabled"
        - "modify sys global-settings remote-host add {guest2.example.com {hostname guest2.example.com addr 10.146.142.11}}"
        - "modify sys global-settings remote-host add {guest1.example.com {hostname guest1.example.com addr 10.146.142.10}}"
        - "run /util bash -c \"bigstart remove named\""
        - "run /util bash -c \"bigstart remove zxfrd\""
        - "run /util bash -c \"openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj '/C=US/ST=OH/L=Columbus/O=My Company/OU=Network Services/CN=`uname -n`' -keyout /config/httpd/conf/ssl.key/server.key -out /config/httpd/conf/ssl.crt/server.crt -sha256\""
        - "run /util bash -c \"cat /config/httpd/conf/ssl.crt/server.crt > /config/big3d/client.crt\""
        - "run /util bash -c \"cat /config/httpd/conf/ssl.crt/server.crt > /config/gtm/server.crt\""
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "REST call DO declaration guest2"
    uri:
      url: "https://{{bigip_ip_guest2}}:{{bigip_port}}/mgmt/shared/declarative-onboarding"
      method: POST
      body: "{{ lookup('template','../templates/DO_declaration_template_guest_BIG-IP.json') }}"
      headers:
        Content-Type: "application/json"
      return_content: yes
      body_format: json
      status_code: 202
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_output
    vars:
      DO_vars:
        hostname: "guest2.example.com"
        trusthostname: "guest1.example.com"
        trustremoteHostname: "guest2.example.com"
        trustremote: "/Common/failoverGroup/members/0"
        remotehost: "10.146.142.10"
        ntpServers:
          - 45.33.103.94
          - 72.87.88.202
          - 129.250.35.251
        selfIPs:
          first:
            self: 
              name: VLAN33
              address: 10.0.23.3/24
              vlan: VLAN33
            float:
              name: VLAN33-Floating
              address: 10.0.23.1/24
              vlan: VLAN33
          second:
            self: 
              name: VLAN34
              address: 10.0.24.3/24
              vlan: VLAN34
            float:
              name: VLAN34-Floating
              address: 10.0.24.1/24
              vlan: VLAN34
          third:
            self: 
              name: Failover
              address: 10.3.3.2/30
              vlan: Failover-57_58
            float:
              name: 
              address: 
              vlan: 
        tacacs:
          servers:
            - 10.4.1.1
            - 10.5.1.1
          secret: secret
        snmpAgent:
          contact: NOC 877-555-5555
          location: DataCenter3.0, Location Datacenter vCMP Guest
          allowList:
            - 10.1.1.0/24
            - 10.2.2.0/24
            - 10.3.3.0/24
            - 10.4.4.0/24
    delegate_to: localhost

  - set_fact:
      DO_taskID_guest2: "{{ DO_output.json.selfLink.split('/')[-1] }}"

  - name: "REST call DO declaration guest1"
    uri:
      url: "https://{{bigip_ip_guest1}}:{{bigip_port}}/mgmt/shared/declarative-onboarding"
      method: POST
      body: "{{ lookup('template','../templates/DO_declaration_template_guest_BIG-IP.json') }}"
      headers:
        Content-Type: "application/json"
      return_content: yes
      body_format: json
      status_code: 202
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_output
    vars:
      DO_vars:
        hostname: "guest1.example.com"
        trusthostname: "guest1.example.com"
        trustremoteHostname: "guest2.example.com"
        trustremote: "/Common/failoverGroup/members/1"
        ntpServers:
          - 45.33.103.94
          - 72.87.88.202
          - 129.250.35.251
        selfIPs:
          first:
            self: 
              name: VLAN33
              address: 10.0.23.2/24
              vlan: VLAN33
            float:
              name: VLAN33-Floating
              address: 10.0.23.1/24
              vlan: VLAN33
          second:
            self: 
              name: VLAN34
              address: 10.0.24.2/24
              vlan: VLAN34
            float:
              name: VLAN34-Floating
              address: 10.0.24.1/24
              vlan: VLAN34
          third:
            self: 
              name: Failover
              address: 10.3.3.1/30
              vlan: Failover-57_58
            float:
              name: 
              address: 
              vlan: 
        tacacs:
          servers:
            - 10.4.1.1
            - 10.5.1.1
          secret: secret
        snmpAgent:
          contact: NOC 877-555-5555
          location: DataCenter3.0, Location Datacenter vCMP Guest
          allowList:
            - 10.1.1.0/24
            - 10.2.2.0/24
            - 10.3.3.0/24
            - 10.4.4.0/24
    delegate_to: localhost

  - set_fact:
      DO_taskID_guest1: "{{ DO_output.json.selfLink.split('/')[-1] }}"


  - name: Wait a maximum of 300 seconds for guests to be ready to take configuration after initial DO POST
    bigip_wait:
      timeout: 300
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - name: "REST to check for Successfull DO Declaration guest2"
    uri:
      url: "https://{{bigip_ip_guest2}}:{{bigip_port}}/mgmt/shared/declarative-onboarding/task/{{DO_taskID_guest2}}"
      method: GET
      return_content: yes
      status_code: [200, 202]
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_task_check
    until: DO_task_check.json.result.message.find("success") != -1
    retries: 40
    delay: 15

  - name: "REST to check for Successfull DO Declaration guest1"
    uri:
      url: "https://{{bigip_ip_guest1}}:{{bigip_port}}/mgmt/shared/declarative-onboarding/task/{{DO_taskID_guest1}}"
      method: GET
      return_content: yes
      status_code: [200, 202]
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_task_check
    until: DO_task_check.json.result.message.find("success") != -1
    retries: 40
    delay: 15
    delegate_to: localhost

  - name: "REST call DO declaration guest1, second POST"
    uri:
      url: "https://{{bigip_ip_guest1}}:{{bigip_port}}/mgmt/shared/declarative-onboarding"
      method: POST
      body: "{{ lookup('template','../templates/DO_declaration_template_guest_BIG-IP.json') }}"
      headers:
        Content-Type: "application/json"
      return_content: yes
      body_format: json
      status_code: 202
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_output
    vars:
      DO_vars:
        hostname: "guest1.example.com"
        trusthostname: "guest1.example.com"
        trustremoteHostname: "guest2.example.com"
        trustremote: "/Common/failoverGroup/members/1"
        ntpServers:
          - 45.33.103.94
          - 72.87.88.202
          - 129.250.35.251
        selfIPs:
          first:
            self: 
              name: VLAN33
              address: 10.0.23.2/24
              vlan: VLAN33
            float:
              name: VLAN33-Floating
              address: 10.0.23.1/24
              vlan: VLAN33
          second:
            self: 
              name: VLAN34
              address: 10.0.24.2/24
              vlan: VLAN34
            float:
              name: VLAN34-Floating
              address: 10.0.24.1/24
              vlan: VLAN34
          third:
            self: 
              name: Failover
              address: 10.3.3.1/30
              vlan: Failover-57_58
            float:
              name: 
              address: 
              vlan: 
        tacacs:
          servers:
            - 10.4.1.1
            - 10.5.1.1
          secret: secret
        snmpAgent:
          contact: NOC 877-555-5555
          location: DataCenter3.0, Location Datacenter vCMP Guest
          allowList:
            - 10.1.1.0/24
            - 10.2.2.0/24
            - 10.3.3.0/24
            - 10.4.4.0/24
    delegate_to: localhost

  - name: "Wait a maximum of 300 seconds for guests to be ready"
    bigip_wait:
      timeout: 300
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost

  - set_fact:
      DO_taskID: "{{ DO_output.json.selfLink.split('/')[-1] }}"

  - name: "REST to check for Successfull DO Declaration"
    uri:
      url: "https://{{bigip_ip_guest1}}:{{bigip_port}}/mgmt/shared/declarative-onboarding/task/{{DO_taskID}}"
      method: GET
      return_content: yes
      status_code: [200, 202]
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_task_check
    until: DO_task_check.json.result.message.find("success") != -1
    retries: 40
    delay: 15
    delegate_to: localhost

  - name: "BIG-IP imish config guests"
    bigip_imish_config:
      lines:
        - no service password-encryption
        - log file /var/log/zebos.log
        - no banner motd
        - bgp extended-asn-cap 
        - router bgp 65010
        - bgp router-id 10.1.1.1
        - bgp graceful-restart restart-time 120
        - redistribute kernel route-map route_map__1_name
        - timers bgp 10 35
        - neighbor Neighbor_IN peer-group
        - neighbor Neighbor_IN soft-reconfiguration inbound
        - neighbor Neighbor_IN route-map route_map__2_name out
        - neighbor Neighbor_IN remote-as 65020
        - neighbor Neighbor_OUT peer-group
        - neighbor Neighbor_OUT soft-reconfiguration inbound
        - neighbor Neighbor_OUT route-map  route_map__3_name out
        - neighbor Neighbor_OUT remote-as 65020
        - neighbor 10.1.1.2 peer-group Neighbor_OUT
        - neighbor 10.1.1.3 peer-group Neighbor_OUT
        - neighbor 10.1.1.4 peer-group Neighbor_IN
        - neighbor 10.1.1.5 peer-group Neighbor_IN
        - ip as-path access-list access_list__1_name permit ^65001 *
        - ip as-path access-list access_list__2_name permit ^$
        - ip as-path access-list access_list__2_name permit ^65005$
        - ip prefix-list prefix_list__1_name seq 10 permit 10.2.2.0/24 ge 32
        - route-map route_map__3_name permit 10
        -  match as-path access_list__2_name
        - route-map route_map__2_name permit 10
        -  match as-path access_list__1_name
        - route-map route_map__1_name permit 50
        -  match ip address prefix-list prefix_list__1_name
      provider:
        server: "{{item}}"
        password: "{{bigip_password}}"
        user: "{{bigip_username}}"
        server_port: "{{bigip_port}}"
        validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost


  - name: "REST call AS3 declaration guests"
    uri:
      url: "https://{{item}}:{{bigip_port}}/mgmt/shared/appsvcs/declare"
      method: POST
      body: "{{lookup('file','../templates/as3Declaration.json')}}"
      headers:
        Content-Type: "application/json"
      return_content: yes
      body_format: json
      status_code: 200
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    with_items:
      - "{{bigip_ip_guest1}}"
      - "{{bigip_ip_guest2}}"
    delegate_to: localhost




